### ISSUE TITLE
BuildCraft API 已在2014年12月10日以MIT许可证重新授权

### ISSUE THREAD

**Issue by nightovl** [CalenXwX/BuildCraft#7]
参见：
https://github.com/BuildCraft/BuildCraft/issues/2248
我注意到 1.18.2 BuildCraft API部分代码的许可证重新变回MMPLv1。
https://github.com/CalenXwX/BuildCraftAPI/blob/9efe5972161da7c7726519bbe033c0f395d18a47/resources/LICENSE.API
这里是BuildCraft API所用的许可证，实际上是MIT许可证。

BuildCraft本体除了机器人以外的代码都在1.12.2被AlexIIL重写并改用MPLv2许可证了，没重写的机器人部分也得到了授权改用MPLv2许可证了，说是因为MMPLv1许可证有缺陷。
https://github.com/BuildCraft/BuildCraft/issues/3004

仍以MMPLv1开源的1.12.2代码在这里，貌似现在已经不用了，据说编译出jar文件根本没用到这一部分代码。
https://github.com/BuildCraft/BuildCraft/tree/8.0.x-1.12.2/src_old_license/buildcraft

考古学家()

**Comment by night0v0** [comment]
心血来潮想编辑一下BC的mc百科信息时发现这里改了(｀・ω・´)。

![mmexport1722656889396](https://github.com/user-attachments/assets/068dfe45-d8e0-429e-b625-32ee64676b4e)

**Comment by night0v0** [comment]
心血来潮想编辑一下BC的mc百科信息时发现这里改了（￣▽￣）
![Uploading mmexport1722657593425.jpg…]()

**Comment by nightovl** [comment]
心血来潮想编辑一下BC的mc百科信息时发现这里改了（￣▽￣）。
![mmexport1722657593425](https://github.com/user-attachments/assets/94579e08-bb6f-45b4-b8dd-9bab88e76f17)

**Comment by AartBluestoke** [comment]
to be clear, the code *as it was in 2014* was MIT licenced. 
All code updates since then have been released under a new licence, and what exists today is quite incompatible with that specific version. 
The MIT licence does not prevent re-licencing under new terms, and the general Minecraft Modding community switched to the MMPL to avoid issues concerning copyright and other issues with reverse engineering and interfacing with what is otherwise a private binary.

**Comment by nightovl** [comment]
MIT许可证允许新增代码更改许可证，所以可以重启MMPLv1许可证。不过以前的BC团队为了舍弃MMPLv1这个许可证花了很大功夫（甚至issue#3004至今仍未关闭），既然代码最终要合并到BC仓库，BuildCraft API还是使用原来的MIT许可证比较好。

**Comment by CalenXwX** [comment]
API里的license改回1.12.2那样啦
大概是改格式的时候复制粘贴没仔细看粘过来的东西不一样xwx

又看了以下 1.12.2的API里 一部分写的是MIT 一部分还是MMPLv1诶
比如[https://github.com/BuildCraft/BuildCraftAPI/blob/8.0.x-1.12.2/api/buildcraft/api/core/IStackFilter.java](https://github.com/BuildCraft/BuildCraftAPI/blob/8.0.x-1.12.2/api/buildcraft/api/core/IStackFilter.java)
